<?php

namespace Database\Seeders;

use App\Models\mood;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class moodSeeder extends Seeder
{
    public function run(): void
    {
        $moods = [
            [
                'mood_key' => "sedih",
                'sort_order' => 1,
                'feeling' => "Sedih",
                'nuance' => "Emosi paling jujur",
                'song' => "Aku Harus Pergi",
                'question' => "Apa yang paling membuatmu merasa sedih?",
                'choice_1' => "Ada seseorang yang harus aku lepaskan",
                'choice_2' => "Aku baru kehilangan sesuatu yang berarti",
                'choice_3' => "Ada sesuatu yang belum bisa kulupakan",
                'choice_4' => "Tidak tahu kenapa, hanya sedang merasa sedih",
                'answer' => "Jawabanmu : seseorang yang harus aku lepaskan",
                'coordinate' => "Titik untuk saatnya kamu refleksi diri 💙",
                'why' => "Aku Harus Pergi berbicara tentang keberanian untuk menepi sejenak, mengambil jarak, dan memberi diri sendiri ruang untuk memahami apa yang sebenarnya kita rasakan.",
                'affirmation' => "Tidak apa-apa untuk tidak baik-baik saja. Tidak apa-apa jika kamu ingin menepi sebentar, mengambil jarak dari sesuatu yang selama ini terlalu dekat, dan memberi dirimu waktu untuk bernapas. Kamu tidak harus selalu bertahan hanya karena sudah berjalan sejauh ini. Ada kalanya, pergi bukan berarti menyerah atau berhenti peduli. Bisa jadi, itu adalah cara paling jujur untuk mengakui bahwa kamu juga perlu dijaga.Jadi, kalau hari ini kamu belum tahu harus ke mana, tidak apa-apa. Pergilah sejauh yang kamu butuhkan, menepilah selama yang kamu perlukan, sampai suatu hari kamu menemukan kembali dirimu yang sempat hilang di perjalanan. Karena mungkin, perjalanan paling penting bukan tentang menemukan tempat untuk dituju, tetapi tentang kembali kepada diri sendiri.",
                'weather_text' => "Mendung setelah hujan 🌩️",
                'audio_path' => "assets/audio/sedih.wav",
                'artwork_path' => "assets/artwork/aku-harus-pergi.jpg",
                'color_primary' => '#528AED',
                'color_secondary' => '#2673F4',
                'color_accent' => '#0A3CCF',
                'color_text' => '#EAF1FF',
                'mof_url' => "https://ffm.to/mapoffeelings",
            ],
            [
                'mood_key' => "serba-salah",
                'sort_order' => 2,
                'feeling' => "Serba Salah",
                'nuance' => "Emosi yang paling sulit dipahami",
                'song' => "Tak Peka",
                'question' => "Apa yang membuatmu merasa serba salah?",
                'choice_1' => "Merasa selalu kurang dan tidak pernah memenuhi ekspektasi orang lain",
                'choice_2' => "Merasa tidak dimengerti",
                'choice_3' => "Selalu dibandingkan dengan orang lain",
                'choice_4' => "Takut keputusan yang diambil akan mengecewakan seseorang",
                'answer' => "Jawabanmu : orang orang yang pernah hadir",
                'coordinate' => "Titik untuk saatnya kamu berdamai dengan diri sendiri 💛",
                'why' => "Tak Peka berbicara tentang rasa lelah ketika kita sudah berusaha memberikan yang terbaik, tetapi apa yang kita berikan tidak selalu diterima seperti yang kita harapkan. Tentang perbedaan cara memahami dan menunjukkan rasa, sampai akhirnya kita mulai mempertanyakan diri sendiri dan merasa selalu kurang di mata orang lain.",
                'affirmation' => "Tidak semua yang kamu berikan akan selalu sampai kepada orang lain dengan cara yang kamu harapkan. Kadang, kamu sudah datang dengan seluruh niat baik yang kamu punya, tetapi tetap terasa salah di mata seseorang yang membutuhkan sesuatu yang berbeda. Dari sana, pelan-pelan kamu mulai bertanya pada diri sendiri: apa yang kurang dariku? Apa yang seharusnya bisa kulakukan lebih baik? Kamu boleh mengakui bahwa ada hal-hal yang tidak kamu pahami. Kamu boleh belajar, berubah, dan menjadi lebih peka. Tetapi jangan sampai keinginan untuk dimengerti membuatmu terus-menerus mengubah dirimu menjadi seseorang yang bukan kamu. Karena tidak semua perbedaan adalah kekurangan, dan tidak semua hal yang berakhir adalah bukti bahwa kamu gagal memberikan yang terbaik. Mungkin, menjadi cukup bukan tentang mampu memberikan segala yang dibutuhkan orang lain. Mungkin, menjadi cukup adalah ketika kamu bisa terus belajar mencintai dengan lebih baik, tanpa harus kehilangan dirimu sendiri di dalamnya.",
                'weather_text' => "Gerimis sepanjang sore 🌧️",
                'audio_path' => "assets/audio/serba-salah.wav",
                'artwork_path' => "assets/artwork/tak-peka.jpg",
                'color_primary' => '#F2921B',
                'color_secondary' => '#AEB247',
                'color_accent' => '#4AB190',
                'color_text' => '#5B2A0A',
                'mof_url' => "https://ffm.to/mapoffeelings",
            ],
            [
                'mood_key' => "curiga",
                'sort_order' => 3,
                'feeling' => "Curiga",
                'nuance' => "Emosi yang paling rapuh",
                'song' => "Tak Mendua",
                'question' => "Apa yang paling membuatmu curiga belakangan ini?",
                'choice_1' => "Sikap seseorang yang tiba-tiba berubah",
                'choice_2' => "Sesuatu yang terasa disembunyikan",
                'choice_3' => "Perhatian yang mulai terasa berbeda",
                'choice_4' => "Perasaan bahwa ada sesuatu yang tidak dikatakan",
                'answer' => "Jawabanmu : sikap yang tiba-tiba terasa berbeda",
                'coordinate' => "Titik untuk kamu belajar untuk mengurai prasangka ✨",
                'why' => "Tak Mendua berbicara tentang rasa curiga yang perlahan tumbuh ketika rasa takut kehilangan mulai mengubah cara kita melihat seseorang. Hal-hal kecil yang sebenarnya sederhana bisa terasa seperti tanda, dan tanpa sadar kita mulai mencari jawaban dari sesuatu yang belum tentu benar. Kadang, yang membuat kita terluka bukan apa yang benar-benar terjadi, tetapi apa yang terus kita bayangkan mungkin terjadi.",
                'affirmation' => "Tidak semua perubahan berarti seseorang sedang meninggalkanmu. Tidak semua jarak menyimpan rahasia, dan tidak setiap hal yang terasa berbeda adalah tanda bahwa ada orang lain di antara kalian. Ada kalanya rasa takut kehilangan membuat kita melihat sesuatu bukan sebagaimana adanya, tetapi sebagaimana yang paling kita takutkan.Kamu boleh merasa takut. Kamu boleh merasa ragu. Tapi sebelum membiarkan prasangka menjawab semuanya, beri ruang untuk bertanya, mendengar, dan memahami. Karena percaya bukan berarti tidak pernah curiga. Percaya adalah ketika kita memilih untuk mencari kebenaran tanpa membiarkan ketakutan lebih dulu menentukan apa yang harus kita percaya.Jangan biarkan sesuatu yang belum terjadi mengambil tempat dari sesuatu yang sedang kamu miliki.",
                'weather_text' => "Mendung Tanpa Hujan 🌫️",
                'audio_path' => "assets/audio/curiga.wav",
                'artwork_path' => "assets/artwork/tak-mendua.jpg",
                'color_primary' => '#F59F7B',
                'color_secondary' => '#BEC799',
                'color_accent' => '#B9CCA1',
                'color_text' => '#2B4B2E',
                'mof_url' => "https://ffm.to/mapoffeelings",
            ],
            [
                'mood_key' => "lelah",
                'sort_order' => 4,
                'feeling' => "Lelah",
                'nuance' => "Emosi yang paling menguras diri",
                'song' => "Hilang Warasnya",
                'question' => "Apa yang paling membuatmu lelah akhir-akhir ini?",
                'choice_1' => "Terus-menerus menghadapi hal yang sama",
                'choice_2' => "Merasa tidak pernah didengar atau dipahami",
                'choice_3' => "Terlalu lama mengalah demi keadaan",
                'choice_4' => "Berusaha bertahan di sesuatu yang terus menyakitkan",
                'answer' => "Jawabanmu : hal yang terus berulang dan menguras diri",
                'coordinate' => "Titik untuk saatnya kamu melepaskan 🤍",
                'why' => "Hilang Warasnya berbicara tentang saat sesuatu yang terus berulang mulai mengambil terlalu banyak dari diri kita. Tentang ketika kita sudah mencoba memahami, menghadapi, dan bertahan, tetapi yang tersisa justru rasa lelah yang perlahan mengubah cara kita melihat semuanya.",
                'affirmation' => "Tidak semua hal harus terus kamu hadapi hanya karena kamu sudah terbiasa menjalaninya. Ada saatnya kamu perlu mengakui bahwa sesuatu telah mengambil terlalu banyak dari dirimu, sampai kamu tidak lagi mengenali dirimu sendiri di dalamnya. Kamu boleh berhenti, mengambil jarak, dan meletakkan apa yang selama ini kamu paksa untuk tetap kamu bawa. Mungkin selama ini kamu mengira bertahan adalah satu-satunya cara untuk membuktikan bahwa sesuatu masih layak diperjuangkan. Padahal, ada hal-hal yang justru semakin kita pertahankan, semakin banyak bagian dari diri kita yang harus dikorbankan. Dan tidak semua yang pernah kita perjuangkan harus berakhir dengan kita tetap tinggal.Karena menjaga kewarasan bukan tentang seberapa lama kamu mampu bertahan, tetapi tentang keberanian untuk tahu kapan dirimu sudah cukup lelah untuk terus dipaksa.",
                'weather_text' => "Langit Terik Tanpa Angin ☀️🥵",
                'audio_path' => "assets/audio/lelah.wav",
                'artwork_path' => "assets/artwork/hilang-warasnya.jpg",
                'color_primary' => '#B79C90',
                'color_secondary' => '#AE8475',
                'color_accent' => '#9A4735',
                'color_text' => '#FFC98A',
                'mof_url' => "https://ffm.to/mapoffeelings",
            ],
            [
                'mood_key' => "kesepian",
                'sort_order' => 10,
                'feeling' => "Kesepian",
                'nuance' => "Emosi yang paling kosong",
                'song' => "Sumpah Percuma",
                'question' => "Di tengah semua yang sudah kamu punya, apa yang masih terasa kosong?",
                'choice_1' => "Ada yang ingin kubagi, tapi tak tahu dengan siapa",
                'choice_2' => "Ingin merasa benar-benar dipahami",
                'choice_3' => "Ingin punya seseorang untuk pulang",
                'choice_4' => "Ada ruang dalam diri yang belum terisi",
                'answer' => "Jawabanmu : ruang dalam diri yang belum terisi",
                'coordinate' => "Titik pencarian rumah untuk pulang 🏠",
                'why' => "Sumpah Percuma berbicara tentang kesepian yang bisa hadir bahkan ketika hidup terlihat penuh. Tentang mengejar mimpi, memiliki banyak hal, dan terus berjalan seolah kita baik-baik saja, tetapi tetap merasakan ada ruang yang belum terisi ketika semuanya menjadi sunyi.",
                'affirmation' => "Tidak semua kekosongan harus segera diisi. Ada ruang-ruang dalam diri yang tidak bisa ditutup hanya dengan kesibukan, pencapaian, atau hadirnya banyak orang. Kamu boleh mengakui bahwa di tengah semua yang sudah kamu punya, masih ada sesuatu yang kamu rindukan. Bukan karena hidupmu kurang, tetapi karena menjadi manusia berarti selalu ada bagian dari diri kita yang masih mencari, masih bertanya, masih ingin merasa dekat dengan sesuatu yang benar-benar berarti.Mungkin kamu tidak perlu terburu-buru menemukan jawabannya. Biarkan ruang itu ada untuk sementara. Biarkan dirimu merasakan sepinya tanpa buru-buru menganggapnya sebagai kekurangan.Sebab, tidak semua yang kosong harus segera diisi. Ada kekosongan yang justru mengajarkan kita apa yang benar-benar kita butuhkan, dan ada kerinduan yang tidak datang untuk membuat hidup kita lengkap, melainkan untuk menunjukkan ke mana hati kita ingin pulang.",
                'weather_text' => "Malam yang sangat panjang 🌙",
                'audio_path' => "assets/audio/kesepian.wav",
                'artwork_path' => "assets/artwork/sumpah-percuma.jpg",
                'color_primary' => '#7EAAFD',
                'color_secondary' => '#B99EFD',
                'color_accent' => '#DB9EFD',
                'color_text' => '#F5F3FF',
                'mof_url' => "https://ffm.to/mapoffeelings",
            ],
            [
                'mood_key' => "berduka",
                'sort_order' => 5,
                'feeling' => "Berduka",
                'nuance' => "Emosi yang paling pilu",
                'song' => "Pesan Rindu",
                'question' => "Apabila dapat mengulang satu momen, apa yang paling ingin kamu lakukan?",
                'choice_1' => "Mengucapkan selamat tinggal dengan cara yang lebih baik",
                'choice_2' => "Mendengar suaranya sekali lagi",
                'choice_3' => "Memeluknya lebih lama",
                'choice_4' => "Mengatakan semua yang belum sempat disampaikan",
                'answer' => "suaranya yang ingin kudengar sekali lagi",
                'coordinate' => "Titik untuk mengenang mereka yang sudah tiada 🕊️",
                'why' => "Pesan Rindu berbicara tentang kehilangan seseorang yang pernah menjadi bagian besar dalam hidup kita, dan tentang bagaimana kenangan menjadi satu-satunya cara untuk kembali mendekati mereka. Tentang foto-foto yang masih tersimpan, cerita yang masih kita ingat, dan momen-momen kecil yang tiba-tiba terasa begitu berarti setelah seseorang tidak lagi bisa kita temui.",
                'affirmation' => "Tidak apa-apa jika sampai hari ini kamu masih merindukan seseorang yang sudah tidak bisa kamu temui. Tidak apa-apa jika ada hari-hari ketika sebuah foto, lagu, tempat, atau kenangan kecil tiba-tiba membawa mereka kembali ke dalam pikiranmu. Kamu tidak harus terburu-buru melupakan hanya karena waktu terus berjalan.\\r\\n\\r\\nAda orang-orang yang mungkin sudah tidak lagi berjalan bersama kita, tetapi bukan berarti mereka benar-benar hilang dari hidup kita. Mereka tinggal dalam cerita yang pernah kita buat, dalam kebiasaan yang pernah mereka tinggalkan, dalam hal-hal kecil yang tanpa sadar masih kita lakukan karena pernah belajar darinya.\\r\\n\\r\\nMungkin kehilangan memang tidak pernah benar-benar tentang belajar melupakan. Mungkin, pada akhirnya, kita hanya belajar membawa seseorang dalam bentuk yang berbeda: tidak lagi di samping kita, tetapi tetap hidup di dalam ingatan, di dalam doa, dan di dalam rindu yang kita simpan.",
                'weather_text' => "Senja yang Perlahan Redup 🌅",
                'audio_path' => "assets/audio/berduka.wav",
                'artwork_path' => "assets/artwork/pesan-rindu.jpg",
                'color_primary' => '#FEE5B0',
                'color_secondary' => '#FDD986',
                'color_accent' => '#FEC75B',
                'color_text' => '#7A3A12',
                'mof_url' => "https://ffm.to/mapoffeelings",
            ],
            [
                'mood_key' => "nyaman",
                'sort_order' => 6,
                'feeling' => "Berbunga-bunga",
                'nuance' => "Emosi yang paling manis",
                'song' => "YTTA",
                'question' => "Apa yang membuat sesuatu terasa begitu istimewa, meski sederhana?",
                'choice_1' => "Punya bahasa kecil yang hanya kalian mengerti",
                'choice_2' => "Saling sayang tanpa perlu banyak kata",
                'choice_3' => "Momen sederhana yang terasa istimewa",
                'choice_4' => "Bisa menikmati hubungan tanpa perlu menjelaskannya kepada siapa pun",
                'answer' => "percakapan yang hanya dipahami berdua",
                'coordinate' => "Titik untuk merayakan hal-hal kecil dalam hidupmu 🧡",
                'why' => "YTTA berbicara tentang rasa yang sedang tumbuh, ketika seseorang mulai menemukan sesuatu yang terasa istimewa tanpa perlu buru-buru memberinya nama. Tentang menikmati perhatian kecil, bahasa yang hanya dimengerti berdua, dan momen-momen sederhana yang entah kenapa terasa lebih berarti ketika dijalani bersama seseorang.",
                'affirmation' => "Tidak semua hal yang berarti harus segera diberi nama. Ada rasa yang cukup dinikmati tanpa harus tahu akan membawamu ke mana. Nikmati percakapan kecil, tawa yang hanya kalian mengerti, genggaman yang terasa sederhana tetapi membuat hari menjadi lebih baik.\\r\\n\\r\\nKamu tidak harus terburu-buru memastikan apakah sesuatu akan bertahan selamanya. Untuk sekarang, mungkin cukup dengan hadir, saling menjaga, dan membiarkan rasa itu tumbuh sebagaimana mestinya.\\r\\n\\r\\nKarena terkadang, bagian paling indah dari sebuah rasa adalah ketika ia belum menjadi apa-apa bagi dunia, tetapi sudah menjadi sesuatu yang begitu berarti bagi kalian.",
                'weather_text' => "Siang Hari yang Cerah 🌞",
                'audio_path' => "assets/audio/nyaman.wav",
                'artwork_path' => "assets/artwork/ytta.jpg",
                'color_primary' => '#7ECBC0',
                'color_secondary' => '#F5C150',
                'color_accent' => '#FE9B72',
                'color_text' => '#33413A',
                'mof_url' => "https://ffm.to/mapoffeelings",
            ],
            [
                'mood_key' => "terharu",
                'sort_order' => 7,
                'feeling' => "Nostalgia",
                'nuance' => "Emosi yang paling membekas",
                'song' => "Sedih Harus Kau Buang",
                'question' => "Saat bernostalgia, hal apa yang paling sering kamu rindukan?",
                'choice_1' => "Tawa dan canda yang pernah dibagi",
                'choice_2' => "Orang-orang yang pernah hadir",
                'choice_3' => "Momen sederhana yang dulu terasa biasa",
                'choice_4' => "Suasana dari masa yang tak bisa diulang",
                'answer' => "kenangan yang perlahan kubawa berdamai",
                'coordinate' => "Titik untuk melepas memori dengan hangat🌤️",
                'why' => "Sedih Harus Kau Buang berbicara tentang masa-masa yang pernah kita jalani bersama orang-orang yang pernah begitu dekat. Tentang tawa, kenakalan, kesalahan, cerita kecil, dan momen-momen sederhana yang dulu terasa biasa, tetapi perlahan menjadi bagian dari kenangan yang paling berharga.",
                'affirmation' => "Waktu mungkin akan membawa kita semakin jauh dari hari-hari yang pernah kita jalani bersama. Orang-orang yang dulu selalu ada mungkin akan memiliki kesibukan, jalan, dan kehidupan masing-masing. Bahkan mungkin, suatu hari nanti kita tidak lagi mengingat semua detailnya seperti sekarang.\\r\\n\\r\\nTapi tidak apa-apa. Tidak semua yang pernah berarti harus tetap tinggal untuk selamanya agar bisa disebut berharga. Ada orang-orang yang hadir hanya untuk menemani satu bagian dari perjalanan kita, lalu perlahan berjalan ke arahnya masing-masing.\\r\\n\\r\\nSimpan tawa yang pernah kalian bagi. Maafkan kesalahan yang pernah terjadi. Kenang hal-hal baik yang pernah membuat kalian bahagia. Karena mungkin, cara terbaik untuk menghargai masa lalu bukan dengan berharap semuanya kembali seperti dulu, tetapi dengan tersenyum ketika mengingat bahwa kita pernah memiliki hari-hari seindah itu.",
                'weather_text' => "Langit Jingga di Penghujung Hari 🌅",
                'audio_path' => "assets/audio/terharu.wav",
                'artwork_path' => "assets/artwork/sedih-harus-kau-buang.jpg",
                'color_primary' => '#B5DC7C',
                'color_secondary' => '#7ADC6E',
                'color_accent' => '#71CD8D',
                'color_text' => '#1F4A1B',
                'mof_url' => "https://ffm.to/mapoffeelings",
            ],
            [
                'mood_key' => "penuh-harap",
                'sort_order' => 8,
                'feeling' => "Penuh Harap",
                'nuance' => "Emosi yang paling sulit dipahami",
                'song' => "Fatamorgana",
                'question' => "Apa yang membuatmu terus mencari sesuatu yang belum kamu temukan?",
                'choice_1' => "Rasa penasaran tentang apa yang menunggu di depan",
                'choice_2' => "Keyakinan bahwa masih ada yang belum kutemukan",
                'choice_3' => "Keinginan untuk menemukan sesuatu yang terasa tepat",
                'choice_4' => "Perasaan bahwa perjalanan ini belum selesai",
                'answer' => "harapan yang terus kujaga",
                'coordinate' => "Titik untuk mencari arah yang belum ditemukan 🧭",
                'why' => "Fatamorgana bercerita tentang perjalanan mencari sesuatu yang belum kita temukan. Tentang berjalan tanpa tahu pasti ke mana arah akan membawa, melewati jalan yang samar dan berliku, sambil terus mencoba menemukan sesuatu yang terasa seperti tempat untuk pulang.",
                'affirmation' => "Tidak semua perjalanan memiliki arah yang jelas. Ada kalanya kita sudah berjalan cukup jauh, tetapi tujuan yang kita cari masih terasa samar. Kita mencoba membaca tanda, mengikuti jalan yang ada, bahkan sesekali bertanya apakah kita sedang menuju tempat yang benar atau justru semakin jauh dari yang kita cari.\\r\\n\\r\\nTapi tidak apa-apa. Tidak semua hal dalam hidup harus langsung memiliki jawaban. Ada hal-hal yang memang baru bisa kita pahami setelah melewati perjalanan yang panjang. Ada pertemuan yang belum waktunya terjadi, ada tempat yang belum waktunya kita temukan, dan ada jalan yang mungkin harus kita lewati sendiri sebelum akhirnya mengerti ke mana kita sebenarnya ingin pulang.\\r\\n\\r\\nJadi, jika hari ini arahmu masih terasa abu-abu, jangan terlalu cepat menganggap dirimu tersesat. Mungkin kamu hanya sedang berada di bagian perjalanan yang belum memperlihatkan tujuannya. Teruslah melangkah sejauh yang kamu mampu. Karena terkadang, yang kita butuhkan bukan peta yang menunjukkan seluruh jalan, melainkan keberanian untuk percaya pada satu langkah berikutnya.",
                'weather_text' => "Langit Kelabu Setelah Senja ☁",
                'audio_path' => "assets/audio/penuh-harap.wav",
                'artwork_path' => "assets/artwork/fatamorgana.jpg",
                'color_primary' => '#F0AE51',
                'color_secondary' => '#DF842D',
                'color_accent' => '#999C47',
                'color_text' => '#FFF176',
                'mof_url' => "https://ffm.to/mapoffeelings",
            ],
            [
                'mood_key' => "hampa",
                'sort_order' => 9,
                'feeling' => "Hampa",
                'nuance' => "Emosi yang paling kosong",
                'song' => "Sorak Sepi",
                'question' => "Apa yang biasanya membuatmu merasa hampa?",
                'choice_1' => "Kehilangan sesuatu yang dulu berarti",
                'choice_2' => "Tidak menemukan arti dari apa yang dijalani",
                'choice_3' => "Merasa sendiri meski tidak benar-benar sendirian",
                'choice_4' => "Ada bagian diri yang belum bisa kupahami",
                'answer' => "tawa yang ramai tapi hati tetap jauh",
                'coordinate' => "Titik untuk menemukan rasa di balik kekosongan 🌬️",
                'why' => "Sorak Sepi bercerita tentang rasa hampa yang tidak selalu terlihat dari luar. Tentang berada di tengah keramaian, mendengar begitu banyak suara, tetapi tetap merasa ada bagian dalam diri yang sunyi. Ada sesuatu yang ingin diisi, dipahami, atau ditemukan, tetapi bahkan riuh di sekitar pun tidak selalu mampu menjangkaunya.",
                'affirmation' => "Tidak apa-apa jika ada hari ketika semuanya terasa ramai, tetapi hatimu tetap terasa kosong. Tidak semua ruang di dalam diri harus segera ditemukan jawabannya. Ada hal-hal yang memang membutuhkan waktu untuk kita pahami, dan ada rasa yang baru bisa kita kenali setelah kita berani berhenti sejenak dan mendengarkan diri sendiri.\\r\\n\\r\\nJangan terlalu terburu-buru mengisi setiap ruang kosong hanya karena merasa seharusnya sudah penuh. Mungkin, ada bagian dari dirimu yang tidak sedang meminta untuk diisi, melainkan hanya ingin didengarkan. Dan mungkin, dengan mengenalinya perlahan, kamu akan menemukan bahwa rasa hampa itu bukan akhir dari perjalanan, melainkan sebuah ruang untuk kembali menemukan dirimu sendiri.",
                'weather_text' => "Semilir Angin di Malam Hari 🌒",
                'audio_path' => "assets/audio/hampa.wav",
                'artwork_path' => "assets/artwork/sorak-sepi.jpg",
                'color_primary' => '#4DB79D',
                'color_secondary' => '#3BA888',
                'color_accent' => '#308B75',
                'color_text' => '#EFFFAE',
                'mof_url' => "https://ffm.to/mapoffeelings",
            ],
        ];

        foreach ($moods as $data) {
            mood::updateOrCreate(['mood_key' => $data['mood_key']], $data);
        }
    }
}