<?php

namespace Database\Seeders;

use App\Models\mood;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class moodSeeder extends Seeder
{
    public function run(): void
    {
        $moods = [
            [
                'mood_key' => 'sedih',
                'sort_order' => 1,
                'feeling' => 'Sedih',
                'nuance' => 'Memilih pergi demi diri sendiri',
                'song' => 'Aku Harus Pergi',
                'question' => 'Apa yang paling berat saat kamu memilih pergi demi dirimu sendiri?',
                'choice_1' => 'Meninggalkan seseorang yang masih disayangi',
                'choice_2' => 'Menerima bahwa hubungan telah selesai',
                'choice_3' => 'Berhenti mengharapkan perubahan',
                'choice_4' => 'Meyakini bahwa pergi adalah keputusan yang tepat',
                'coordinate' => 'Titik Patah yang Sunyi',
                'why' => 'Aku Harus Pergi berbicara tentang keberanian memilih pergi, bukan karena rasa sudah hilang, tetapi karena diri sendiri juga perlu diselamatkan.',
                'affirmation' => 'Pergi tidak selalu berarti menyerah. Kadang itu adalah cara pertama untuk kembali memilih dirimu sendiri.',
                'weather_text' => 'Waktu biru',
                'audio_path' => 'assets/audio/sedih.mp3',
                'artwork_path' => 'assets/artwork/aku-harus-pergi.jpg',
                'color_primary' => '#528AED',
                'color_secondary' => '#2673F4',
                'color_accent' => '#0A3CCF',
                'color_text' => '#EAF1FF',
                'mof_url' => 'https://ffm.to/mapoffeelings',
            ],
            [
                'mood_key' => 'serba-salah',
                'sort_order' => 2,
                'feeling' => 'Serba Salah',
                'nuance' => 'Tidak memahami keinginan pasangan',
                'song' => 'Tak Peka',
                'question' => 'Apa yang paling sering membuatmu merasa serba salah dalam hubungan?',
                'choice_1' => 'Takut tidak memahami keinginan pasangan',
                'choice_2' => 'Merasa apa pun yang dilakukan tetap salah',
                'choice_3' => 'Lelah menebak tanpa mendapat penjelasan',
                'choice_4' => 'Bingung antara salah paham atau tidak lagi sejalan',
                'coordinate' => 'Sinyal yang Tak Terbaca',
                'why' => 'Tak Peka mewakili rasa lelah ketika niat baik terus meleset dan kamu merasa selalu salah karena tidak memahami sesuatu yang tak pernah benar-benar dijelaskan.',
                'affirmation' => 'Kamu tidak harus terus menerjemahkan sesuatu yang tidak pernah disampaikan dengan jujur.',
                'weather_text' => 'Hujan statis',
                'audio_path' => 'assets/audio/serba-salah.mp3',
                'artwork_path' => 'assets/artwork/tak-peka.jpg',
                'color_primary' => '#F2921B',
                'color_secondary' => '#AEB247',
                'color_accent' => '#4AB190',
                'color_text' => '#5B2A0A',
                'mof_url' => 'https://ffm.to/mapoffeelings',
            ],
            [
                'mood_key' => 'curiga',
                'sort_order' => 3,
                'feeling' => 'Curiga',
                'nuance' => 'Menguji kesetiaan',
                'song' => 'Tak Mendua',
                'question' => 'Ketika memilih tetap setia, apa yang paling ingin kamu jaga?',
                'choice_1' => 'Kepercayaan dalam hubungan',
                'choice_2' => 'Komitmen yang telah disepakati',
                'choice_3' => 'Perasaan yang hanya ditujukan kepada satu orang',
                'choice_4' => 'Keyakinan bahwa cinta tidak perlu terbagi',
                'coordinate' => 'Titik Uji Kepercayaan',
                'why' => 'Tak Mendua adalah penegasan bahwa kesetiaan bukan sekadar ucapan, tetapi keputusan untuk menjaga kepercayaan dan tetap memilih satu orang.',
                'affirmation' => 'Kesetiaan tidak seharusnya terasa seperti pembelaan tanpa akhir. Hati juga perlu dipercaya.',
                'weather_text' => 'Senja elektrik',
                'audio_path' => 'assets/audio/curiga.mp3',
                'artwork_path' => 'assets/artwork/tak-mendua.jpg',
                'color_primary' => '#F59F7B',
                'color_secondary' => '#BEC799',
                'color_accent' => '#B9CCA1',
                'color_text' => '#2B4B2E',
                'mof_url' => 'https://ffm.to/mapoffeelings',
            ],
            [
                'mood_key' => 'lelah',
                'sort_order' => 4,
                'feeling' => 'Lelah',
                'nuance' => 'Terjebak dalam hubungan yang tidak sehat',
                'song' => 'Hilang Warasnya',
                'question' => 'Apa yang paling sulit saat terjebak dalam hubungan yang tidak sehat?',
                'choice_1' => 'Melepaskan seseorang yang terus menyakiti',
                'choice_2' => 'Menyadari bahwa hubungan ini tidak lagi sehat',
                'choice_3' => 'Kehilangan diri sendiri secara perlahan',
                'choice_4' => 'Tidak mengetahui kapan keadaan mulai berubah',
                'coordinate' => 'Garis Retak',
                'why' => 'Hilang Warasnya menggambarkan kelelahan ketika hubungan perlahan mengikis ketenangan, kepercayaan, dan rasa mengenali diri sendiri.',
                'affirmation' => 'Kamu tidak harus kehilangan dirimu sendiri untuk mempertahankan sebuah hubungan.',
                'weather_text' => 'Hangat yang memudar',
                'audio_path' => 'assets/audio/lelah.mp3',
                'artwork_path' => 'assets/artwork/hilang-warasnya.jpg',
                'color_primary' => '#B79C90',
                'color_secondary' => '#AE8475',
                'color_accent' => '#9A4735',
                'color_text' => '#FFC98A',
                'mof_url' => 'https://ffm.to/mapoffeelings',
            ],
            [
                'mood_key' => 'kesepian',
                'sort_order' => 5,
                'feeling' => 'Kesepian',
                'nuance' => 'Pencapaian yang terasa kosong',
                'song' => 'Sumpah Percuma',
                'question' => 'Kapan terakhir kali kamu memiliki banyak hal, tetapi tetap merasa kosong?',
                'choice_1' => 'Saat seluruh pencapaian terasa biasa saja',
                'choice_2' => 'Saat dikelilingi banyak hal tetapi tetap kesepian',
                'choice_3' => 'Saat berhasil memperoleh hal yang dahulu diinginkan',
                'choice_4' => 'Saat menyadari bahwa kebahagiaan tidak selalu menyertai pencapaian',
                'coordinate' => 'Ruang Trofi yang Kosong',
                'why' => 'Sumpah Percuma hadir untuk momen ketika pencapaian terlihat penuh dari luar, tetapi tidak menjawab ruang kosong di dalam diri.',
                'affirmation' => 'Tidak semua yang dirayakan orang lain mampu mengisi bagian dalam dirimu.',
                'weather_text' => 'Kabut sunyi',
                'audio_path' => 'assets/audio/kesepian.mp3',
                'artwork_path' => 'assets/artwork/sumpah-percuma.jpg',
                'color_primary' => '#7EAAFD',
                'color_secondary' => '#B99EFD',
                'color_accent' => '#DB9EFD',
                'color_text' => '#F5F3FF',
                'mof_url' => 'https://ffm.to/mapoffeelings',
            ],
            [
                'mood_key' => 'berduka',
                'sort_order' => 6,
                'feeling' => 'Berduka',
                'nuance' => 'Merindukan seseorang yang telah tiada',
                'song' => 'Pesan Rindu',
                'question' => 'Apabila dapat mengulang satu momen, apa yang paling ingin kamu lakukan?',
                'choice_1' => 'Mengucapkan selamat tinggal dengan lebih baik',
                'choice_2' => 'Mendengar suaranya sekali lagi',
                'choice_3' => 'Memeluknya lebih lama',
                'choice_4' => 'Mengatakan bahwa kerinduan itu masih ada',
                'coordinate' => 'Pesan yang Tetap Tinggal',
                'why' => 'Pesan Rindu menjadi ruang untuk rindu yang tidak lagi dapat disampaikan langsung, tetapi tetap hidup dalam ingatan.',
                'affirmation' => 'Sebagian pesan tidak membutuhkan balasan. Ia tinggal karena rasa sayang masih mengingat jalan pulang.',
                'weather_text' => 'Cahaya sore',
                'audio_path' => 'assets/audio/berduka.mp3',
                'artwork_path' => 'assets/artwork/pesan-rindu.jpg',
                'color_primary' => '#FEE5B0',
                'color_secondary' => '#FDD986',
                'color_accent' => '#FEC75B',
                'color_text' => '#7A3A12',
                'mof_url' => 'https://ffm.to/mapoffeelings',
            ],
            [
                'mood_key' => 'nyaman',
                'sort_order' => 7,
                'feeling' => 'Nyaman',
                'nuance' => 'Hubungan intim yang cukup diketahui berdua',
                'song' => 'Yang Tau-Tau Aja',
                'question' => 'Apa yang paling berharga dari hubungan yang cukup diketahui oleh kalian berdua?',
                'choice_1' => 'Percakapan yang hanya dipahami berdua',
                'choice_2' => 'Tatapan sederhana yang memiliki banyak arti',
                'choice_3' => 'Momen pribadi yang terasa dekat dan intim',
                'choice_4' => 'Kenyamanan tanpa perlu diketahui semua orang',
                'coordinate' => 'Sudut yang Tersembunyi',
                'why' => 'Yang Tau-Tau Aja merayakan hubungan yang intim, hangat, dan tidak membutuhkan pengumuman untuk terasa nyata.',
                'affirmation' => 'Tidak semua perasaan harus diumumkan. Beberapa justru tumbuh paling jujur dalam ruang yang hanya dipahami berdua.',
                'weather_text' => 'Angin rahasia',
                'audio_path' => 'assets/audio/nyaman.mp3',
                'artwork_path' => 'assets/artwork/ytta.jpg',
                'color_primary' => '#7ECBC0',
                'color_secondary' => '#F5C150',
                'color_accent' => '#FE9B72',
                'color_text' => '#33413A',
                'mof_url' => 'https://ffm.to/mapoffeelings',
            ],
            [
                'mood_key' => 'terharu',
                'sort_order' => 8,
                'feeling' => 'Terharu',
                'nuance' => 'Belajar menerima perpisahan',
                'song' => 'Sedih Harus Kau Buang',
                'question' => 'Dalam proses melepaskan, apa yang paling ingin kamu pelajari?',
                'choice_1' => 'Mengikhlaskan bahwa tidak semua hal dapat dipertahankan',
                'choice_2' => 'Berdamai dengan kenangan yang tersisa',
                'choice_3' => 'Menerima perpisahan sebagai bagian dari kehidupan',
                'choice_4' => 'Tetap melangkah meskipun belum sepenuhnya pulih',
                'coordinate' => 'Hari Terakhir di Suatu Tempat',
                'why' => 'Sedih Harus Kau Buang menemani proses melepaskan: bukan menghapus kenangan, melainkan belajar berjalan bersama apa yang pernah ada.',
                'affirmation' => 'Sebagian kesedihan perlu dipeluk, diberi terima kasih, lalu perlahan dilepaskan.',
                'weather_text' => 'Cahaya hari terakhir',
                'audio_path' => 'assets/audio/terharu.mp3',
                'artwork_path' => 'assets/artwork/sedih-harus-kau-buang.jpg',
                'color_primary' => '#B5DC7C',
                'color_secondary' => '#7ADC6E',
                'color_accent' => '#71CD8D',
                'color_text' => '#1F4A1B',
                'mof_url' => 'https://ffm.to/mapoffeelings',
            ],
            [
                'mood_key' => 'penuh-harap',
                'sort_order' => 9,
                'feeling' => 'Penuh Harap',
                'nuance' => 'Percaya bahwa cinta akan menemukan jalan',
                'song' => 'Fatamorgana',
                'question' => 'Apa yang masih membuatmu percaya bahwa cinta yang nyata akan datang?',
                'choice_1' => 'Harapan yang terus dijaga',
                'choice_2' => 'Seseorang yang masih didoakan',
                'choice_3' => 'Keyakinan bahwa waktu yang tepat akan tiba',
                'choice_4' => 'Kepercayaan bahwa ketulusan akan menemukan jalannya',
                'coordinate' => 'Cahaya di Kejauhan',
                'why' => 'Fatamorgana adalah tentang harapan, doa, dan perjalanan mencari tempat pulang yang terasa nyata.',
                'affirmation' => 'Harapan tidak selalu bersuara keras. Kadang ia hanya membuatmu tetap memandang ke arah cahaya.',
                'weather_text' => 'Matahari dari kejauhan',
                'audio_path' => 'assets/audio/penuh-harap.mp3',
                'artwork_path' => 'assets/artwork/fatamorgana.jpg',
                'color_primary' => '#F0AE51',
                'color_secondary' => '#DF842D',
                'color_accent' => '#999C47',
                'color_text' => '#FFF176',
                'mof_url' => 'https://ffm.to/mapoffeelings',
            ],
            [
                'mood_key' => 'hampa',
                'sort_order' => 10,
                'feeling' => 'Hampa',
                'nuance' => 'Sepi di tengah keramaian',
                'song' => 'Sorak Sepi',
                'question' => 'Kapan kamu paling merasa sepi di tengah keramaian?',
                'choice_1' => 'Saat banyak orang hadir tetapi tidak ada yang benar-benar memahami',
                'choice_2' => 'Saat suasana ramai tetapi pikiran tetap kosong',
                'choice_3' => 'Saat tertawa bersama tetapi hati terasa jauh',
                'choice_4' => 'Saat kembali sendiri setelah keramaian berakhir',
                'coordinate' => 'Panggung yang Sunyi',
                'why' => 'Sorak Sepi menggambarkan ruang kosong yang tetap terasa meski suara, tawa, dan banyak orang berada di sekelilingmu.',
                'affirmation' => 'Ruangan paling ramai pun dapat menyisakan sunyi. Perasaanmu tetap nyata, bahkan ketika tidak terlihat.',
                'weather_text' => 'Sorak yang sunyi',
                'audio_path' => 'assets/audio/hampa.mp3',
                'artwork_path' => 'assets/artwork/sorak-sepi.jpg',
                'color_primary' => '#4DB79D',
                'color_secondary' => '#3BA888',
                'color_accent' => '#308B75',
                'color_text' => '#EFFFAE',
                'mof_url' => 'https://ffm.to/mapoffeelings',
            ],
        ];

        foreach ($moods as $data) {
            mood::updateOrCreate(['mood_key' => $data['mood_key']], $data);
        }
    }
}